// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rh.Data;

#nullable disable

namespace Rh.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251223105111_UpdateEmployeForChatbot")]
    partial class UpdateEmployeForChatbot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Rh.Models.BulletinPaie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeId")
                        .HasColumnType("int");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Retenues")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaireBrut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaireNet")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.ToTable("bulletinspaie", (string)null);
                });

            modelBuilder.Entity("Rh.Models.Conge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeId")
                        .HasColumnType("int");

                    b.Property<string>("Motif")
                        .HasColumnType("longtext");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeConge")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.ToTable("conges", (string)null);
                });

            modelBuilder.Entity("Rh.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateArchivage")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateEmbauche")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("EstActif")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("JoursCongesRestants")
                        .HasColumnType("int");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotifArchivage")
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ResponsableRHId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("SalaireBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableRHId");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Rh.Models.ResponsableRH", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstActif")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotDePasseHashChange")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("responsablesrh", (string)null);
                });

            modelBuilder.Entity("Rh.Models.BulletinPaie", b =>
                {
                    b.HasOne("Rh.Models.Employe", "Employe")
                        .WithMany("BulletinsPaie")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("Rh.Models.Conge", b =>
                {
                    b.HasOne("Rh.Models.Employe", "Employe")
                        .WithMany("Conges")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("Rh.Models.Employe", b =>
                {
                    b.HasOne("Rh.Models.ResponsableRH", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableRHId");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("Rh.Models.Employe", b =>
                {
                    b.Navigation("BulletinsPaie");

                    b.Navigation("Conges");
                });
#pragma warning restore 612, 618
        }
    }
}
